export const START_LOADING_PRODUCTS = 'START_LOADING_PRODUCTS'
export const STOP_LOADING_PRODUCTS = 'STOP_LOADING_PRODUCTS'
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS'

export const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES'
export const STOP_LOADING_CATEGORIES = 'STOP_LOADING_CATEGORIES'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const ERROR_CATEGORIES = 'ERROR_CATEGORIES'

export const ADD_SELECTED_CATEGORY = 'ADD_SELECTED_CATEGORY'
export const REMOVE_SELECTED_CATEGORY = 'REMOVE_SELECTED_CATEGORY'
export const REMOVE_ALL_SELECTED_CATEGORIES = 'REMOVE_ALL_SELECTED_CATEGORIES'

export const TOGGLE_LIMITED = 'TOGGLE_LIMITED'
export const TOGGLE_NEW = 'TOGGLE_NEW'
export const SEARCH_CHANGED = 'SEARCH_CHANGED'
export const FILTERS_CLEAR = 'FILTERS_CLEAR'
